"""Pipeline data models.

These dataclasses represent leads at each pipeline stage.
They mirror the Supabase table schemas but live in Python
for type safety and in-process manipulation.

Source enum policy:
    VALID_SOURCES defines the canonical set of collection sources.
    Every candidate must have a source from this set. The backfill
    script (csv_supabase_backfill.py) maps legacy source values
    through map_source() before insert. New collection code must
    use these values directly.
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Optional


# Canonical source values -- must match DB CHECK constraint and repositories.py
VALID_SOURCES = frozenset({
    "google_places",
    "theharvester",
    "manual",
    "serp",
    "html_scrape",
})

# Canonical candidate status values -- must match DB CHECK constraint
VALID_STATUSES = frozenset({
    "new",
    "deduped",
    "sent_to_verify",
    "invalid",
    "duplicate",
})


def validate_source(source: str) -> str:
    """Validate and return source, raising ValueError if invalid."""
    if source not in VALID_SOURCES:
        raise ValueError(
            f"Invalid source '{source}'. Must be one of: {sorted(VALID_SOURCES)}"
        )
    return source


_SOURCE_ALIASES = {
    "google": "google_places",
    "maps": "google_places",
    "places": "google_places",
    "google_maps": "google_places",
    "twitter": "serp",
    "twitter search": "serp",
    "x search": "serp",
    "search": "serp",
    "harvester": "theharvester",
    "the_harvester": "theharvester",
    "html": "html_scrape",
    "scrape": "html_scrape",
    "crawl": "html_scrape",
    "web_scrape": "html_scrape",
}


def normalize_source(source: Optional[str]) -> str:
    """Normalize legacy source values to canonical VALID_SOURCES."""
    if source is None:
        return "manual"
    raw = source.strip()
    if not raw:
        return "manual"
    lowered = raw.lower()
    if lowered in VALID_SOURCES:
        return lowered
    if lowered in _SOURCE_ALIASES:
        return _SOURCE_ALIASES[lowered]
    return raw


def validate_status(status: str) -> str:
    """Validate and return status, raising ValueError if invalid."""
    if status not in VALID_STATUSES:
        raise ValueError(
            f"Invalid status '{status}'. Must be one of: {sorted(VALID_STATUSES)}"
        )
    return status


@dataclass
class Candidate:
    """Stage 1: Raw collected lead, unverified.

    Corresponds to the `candidates` Supabase table.
    """

    # Business identity
    name: str
    name_normalized: str
    source: str  # Must be one of VALID_SOURCES

    # Auto-generated on insert
    id: Optional[str] = None

    # Location
    address: Optional[str] = None
    city: Optional[str] = None
    city_normalized: Optional[str] = None
    state: Optional[str] = None
    country: str = "US"
    lat: Optional[float] = None
    lng: Optional[float] = None

    # Contact (raw, unverified)
    phone_raw: Optional[str] = None
    email_raw: Optional[str] = None
    email_source: Optional[str] = None
    website: Optional[str] = None

    # Collection metadata
    source_id: Optional[str] = None
    collection_batch_id: Optional[str] = None
    collected_at: Optional[datetime] = None
    raw_data: Optional[dict] = None

    # Website analysis
    has_website: Optional[bool] = None
    needs_website: Optional[bool] = None
    needs_redesign: Optional[bool] = None
    needs_chatbot: Optional[bool] = None
    needs_ai_integration: Optional[bool] = None

    # Pipeline state
    status: str = "new"
    dedupe_cluster_id: Optional[str] = None
    dedup_key: Optional[str] = None

    def __post_init__(self):
        self.source = normalize_source(self.source)
        validate_source(self.source)
        validate_status(self.status)

    def to_dict(self) -> dict:
        """Convert to dict for Supabase insert, dropping None values."""
        d = {}
        for k, v in self.__dict__.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                d[k] = v.isoformat()
            else:
                d[k] = v
        # id is auto-generated by Supabase
        d.pop("id", None)
        return d


@dataclass
class VerifiedLead:
    """Stage 2: Verified lead with confidence scores.

    Corresponds to the `verified_leads` Supabase table.
    """

    # Required fields
    name: str
    name_normalized: str
    candidate_ids: list[str] = field(default_factory=list)

    # Auto-generated
    id: Optional[str] = None
    dedupe_cluster_id: Optional[str] = None

    # Location
    address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    country: str = "US"
    lat: Optional[float] = None
    lng: Optional[float] = None

    # Verified contact
    phone: Optional[str] = None
    phone_verified: bool = False
    email: Optional[str] = None
    email_verified: bool = False
    email_confidence: int = 0
    email_source: Optional[str] = None
    website: Optional[str] = None
    website_alive: Optional[bool] = None
    website_last_checked: Optional[datetime] = None

    # Social handles
    linkedin_url: Optional[str] = None
    twitter_handle: Optional[str] = None
    discord_invite: Optional[str] = None
    telegram_handle: Optional[str] = None
    facebook_url: Optional[str] = None
    instagram_handle: Optional[str] = None
    social_source: Optional[str] = None

    # Enrichment
    org_name: Optional[str] = None
    org_industry: Optional[str] = None
    org_employee_count: Optional[int] = None
    org_annual_revenue: Optional[float] = None
    org_linkedin_url: Optional[str] = None
    org_is_hiring: Optional[bool] = None
    tech_stack: Optional[dict] = None

    # Scoring
    needs_score: int = 0
    lead_quality_score: int = 0
    recommended_services: list[str] = field(default_factory=list)

    # Analysis flags
    has_website: bool = False
    needs_website: bool = False
    needs_redesign: bool = False
    needs_chatbot: bool = False
    needs_ai_integration: bool = False

    # Metadata
    verification_batch_id: Optional[str] = None
    verified_at: Optional[datetime] = None
    verification_sources: list[str] = field(default_factory=list)
    data_freshness_days: int = 0
    provenance: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Convert to dict for Supabase insert, dropping None values."""
        d = {}
        for k, v in self.__dict__.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                d[k] = v.isoformat()
            else:
                d[k] = v
        d.pop("id", None)
        return d


# Canonical enrichment tier values
VALID_ENRICHMENT_TIERS = frozenset({"basic", "enriched"})


def validate_enrichment_tier(tier: str) -> str:
    """Validate and return enrichment tier, raising ValueError if invalid."""
    if tier not in VALID_ENRICHMENT_TIERS:
        raise ValueError(
            f"Invalid enrichment_tier '{tier}'. "
            f"Must be one of: {sorted(VALID_ENRICHMENT_TIERS)}"
        )
    return tier


@dataclass
class Pack:
    """Stage 3: Assembled lead pack ready for sale.

    Corresponds to the `packs` Supabase table.
    """

    # Identity
    pack_id: str
    niche: str
    city: str

    # Location
    state: Optional[str] = None
    country: str = "US"

    # Pack contents
    lead_count: int = 0
    enrichment_tier: str = "basic"

    # Quality metrics
    email_coverage: float = 0.0
    phone_coverage: float = 0.0
    avg_lead_quality_score: float = 0.0
    avg_needs_score: float = 0.0

    # Sellability
    sellable: bool = False
    quality_gate_failures: list[str] = field(default_factory=list)

    # Timestamps
    assembled_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None

    # File paths
    csv_path: Optional[str] = None
    jsonl_path: Optional[str] = None

    # Auto-generated
    id: Optional[str] = None

    def __post_init__(self):
        validate_enrichment_tier(self.enrichment_tier)
        if self.assembled_at is None:
            self.assembled_at = datetime.now(tz=None)
        if self.expires_at is None:
            self.expires_at = self.assembled_at + timedelta(days=90)

    def to_dict(self) -> dict:
        """Convert to dict for Supabase insert, dropping None values."""
        d = {}
        for k, v in self.__dict__.items():
            if v is None:
                continue
            if isinstance(v, datetime):
                d[k] = v.isoformat()
            else:
                d[k] = v
        d.pop("id", None)
        return d
